##
## EPITECH PROJECT, 2023
## B-PSU-200-MAR-2-1-42sh-anthony.colombani-gailleur
## File description:
## MAKEFILE
##

NAME	=	gcc *.c -o 42sh -L. -lmy

all:
	$(NAME)
	$(SRC)
	cp 42sh ../
	rm 42sh

clean :
	rm -f $(NAME)

re: clean all.c
